server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8849 #配置nacos地址
        server-addr: localhost:80

#暴露服务
management:
  endpoints:
    web:
      exposure:
        include: '*'
