server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态撞见路由的功能，利用微服务名进行路由
      routes:
        - id: payment_rout          #路由器的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          #filters:
            #- AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加上一堆请求头，名称为X-Request-Id，值为1024
          predicates:
            - Path=/payment/get/**    #断言，路由相匹配的进行路由

        - id: payment_rout2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka #单节点配置
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: gateway9527
    prefer-ip-address: true #访问路径可以显示IP地址
    hostname: cloud-gateway-service

